name: TCC-3385

tasks: 

# Deploy Tibcotunnelroute CR
  - name: deployCR
    type: foreground
    templates:
     - input: "./resources/tibcotunnelrouteCR.yaml"
       output: "./generated/tibcotunnelrouteCR-3385.yaml"
    exec: 
     timeout: 1m
     script: 
        cmd: "kubectl"
        args: ["apply", "-f", "./generated/tibcotunnelrouteCR-3385.yaml"]
        capture:
         stdout:
           - name: output
             match: "((?s).*)"
         stderr:
            - name: outerr
              match: "((?s).*)"
    expect:
     - name: status
       operator: equal
       value: 0

# Status of Tibcotunneroute CR
  - name: tibcotunnelroute-status
    type: foreground
    exec: 
      timeout: 30s
      script: 
        cmd: "kubectl"
        args: ["get", "tibcotunnelroute", "${META_DATA_NAME}", "-n", "${NAMESPACE_TENANT}", "-o", "json"]
        capture: 
          stdout: 
            - name : status_cr
              matchType: jsonpath
              match: "{.status.resource.state}"
    expect:
      - name: status
        operator: equal
        value: 0
      - name: status_cr
        operator: containsStr
        value: "processed"

# Deploy ClientAppn Deployments
  - name: deployClientApp
    type: foreground
    templates: 
      - input: "./resources/client-app.yaml"
        output: "./generated/client-app-3385.yaml"
    exec: 
      timeout: 2m
      script:
        cmd: "kubectl"
        args: ["apply", "-f", "./generated/client-app-3385.yaml"]
    expect:
      - name: status
        operator: equal
        value: 0

# Status of Client Applications
  - name: status_of-clientAppn
    type: foreground
    exec: 
      timeout: 30s
      script: 
        cmd: "kubectl"
        args: ["get", "pods", "-n", "${NAMESPACE_TENANT}", "-o", "json", "--selector=app=http"]
        capture:
          stdout:
            - name: running_state
              matchType: jsonpath
              match: "{.items[*].status.phase}"
            - name: capture_pod_name
              matchType: jsonpath
              match: "{.items[0].metadata.name}"
    expect:
      - name: status
        operator: equal
        value: 0
      - name: running_state
        operator: contains
        value: "Running"
      - name: running_state
        operator: notContains
        value: "Pending"
    repeat:
      count: 6
      until: success
      sleep: 5s  
  - name: sleepCommand
    type: foreground
    exec:
      script:
        cmd: "sleep"
        args: ["15"]

# tibtunnel configuration
  - name: tibTunnelConfigure
    type: foreground
    exec:
      timeout: 5s
      script:
        cmd: "/bin/bash"
        args: ["-c", "./tibtunnel configure -a ${suite.setup.secretKey_hashKey.accesskey}"]   
        capture:
          stdout:
            - name: output
              match: "((?s).*)"
    expect:
      - name: output
        operator: containsStr
        value: "'default' was successfully saved"

# Tibtunnel Connect
  - name: tibtunnelConnect
    type: background
    exec:
      script:
        cmd: "/bin/bash"
        args: ["-c", "timeout 20s ./tibtunnel connect -d --remote-debug -s 8080:localhost:8080 https://${FQDN}/${ENDPOINT} -l ./tibtunnelLog-3385" ]

# Tunnel Status b/w tibtunnel and Client App 
  - name: checkTunnelStatus
    type: foreground
    exec:
      script:
        cmd: "kubectl"
        args: ["exec", "${status_of-clientAppn.capture_pod_name}", "-n${NAMESPACE_TENANT}", "-c", "main", "--", "curl", "-s", "localhost:7778/v1/tunnel/status"]
        capture:
          stdout: 
            - name: output
              match: "((?s).*)"          
    expect:
      - name: output
        operator: containsStr
        value: "\"isConnected\":true"
      - name: output
        operator: notContainsStr
        value: "false"
      - name: output
        operator: containsStr
        value: "Tunnel is connected"
  - name: sleepCommand
    type: foreground
    exec:
      script:
        cmd: "sleep"
        args: ["30"]

teardown: 

# Delete the Tibcotunneroute CR
  - name: delete_yaml_file
    type: foreground
    exec: 
      timeout: 1m
      script:
        cmd: "kubectl"
        args: ["delete", "-f", "./generated/tibcotunnelrouteCR-3385.yaml"]
    expect:
      - name: status
        operator: equal
        value: 0

# Delete the ClientApp Deployments
  - name: delete_yaml_file
    type: foreground
    exec: 
      timeout: 1m
      script:
        cmd: "kubectl"
        args: ["delete", "-f", "./generated/client-app-3385.yaml"]
    expect:
      - name: status
        operator: equal
        value: 0
       
# Verify Tibcotunneroute CR Deletion
  - name: confirm_deletionCR
    type: foreground
    exec: 
      timeout: 1m
      script: 
        cmd: "kubectl"
        args: ["get", "tibcotunnelroute", "-n", "${NAMESPACE_TENANT}", "-o", "json"]
        capture:
          stdout: 
            - name: confirm_deleteCR
              matchType: jsonpath
              match: "{.items[*].metadata.name}"
    expect:
      - name: status
        operator: equal
        value: 0
      - name: confirm_deleteCR
        operator: notContainsStr
        value: "${META_DATA_NAME}"

# Verify ClientApp Deployments deletion
  - name: confirm_deletionA
    type: foreground
    exec: 
      timeout: 1m
      script: 
        cmd: "kubectl"
        args: ["get", "deploy", "-n", "${NAMESPACE_TENANT}", "-o", "json"]
        capture:
          stdout: 
            - name: confirm_deleteA
              matchType: jsonpath
              match: "{.items[*].metadata.name}"
    expect:
      - name: status
        operator: equal
        value: 0
      - name: confirm_deleteA
        operator: notContainsStr
        value: "${META_DATA_NAME}"
    repeat:
      count: 5
      until: success
      sleep: 10ms 

# Verify client-pod deletion
  - name: confirm_client-pod_deletee
    type: foreground
    timeout: 1m
    exec: 
      script: 
        cmd: "kubectl"
        args: ["get", "po", "-n", "${NAMESPACE_TENANT}", "-o", "json"]
        capture:
          stdout: 
            - name: confirm_client-podd
              matchType: jsonpath
              match: "{.items[*].metadata.name}"
    expect:
      - name: status
        operator: equal
        value: 0
      - name: confirm_client-podd
        operator: notContainsStr
        value: "${META_DATA_NAME}"
    repeat:
      count: 12
      until: success
      sleep: 5s  

# Delete log file.
  - name: delete_tibtunnellog
    type: foreground
    exec: 
      timeout: 1m
      script:
        cmd: "/bin/bash"
        args: ["-c", "rm ./tibtunnelLog-3385"]
    expect:
      - name: status
        operator: equal
        value: 0