name: TCC3539
  
tasks:

# Tibtunnel Configure Profile and Verify Profile
  - name: TCC3539_tibTunnelConfigureDefaultProfile
    type: foreground
    exec:
      timeout: 5s
      script:
        cmd: "/bin/bash"
        args: ["-c", "./tibtunnel configure -a ${suite.setup.secretKey_hashKey.accesskey}"]
        # cmd: "${ENV.fnSh}"
        # args: ["configureProfile", "${suite.setup.secretKey_hashKey.accesskey}"]
        capture:
          stdout:
            - name: output
              match: "((?s).*)"
    expect:
      - name: output
        operator: containsStr
        value: "Configuration for profile 'default' was successfully saved"

  - name: TCC3539_verifyProfileSaved
    type: foreground
    exec:
      timeout: 15s
      script:
        # cmd: "${ENV.fnSh}"
        # args: ["verifyProfile"]
        cmd: "/bin/bash"
        args: ["-c", "cat ~/.tibtunnel/credentials"]
        capture:
          stdout:
            - name: output
              match: "((?s).*)"
    expect:
      - name: output
        operator: containsStr
        value: "${suite.setup.secretKey_hashKey.accesskey}"

# Deploy Tibcotunnelroute CR.
  - name: TCC3539_deployCR
    type: foreground
    templates:
     - input: "./resources/tibcotunnelrouteCR.yaml"
       output: "./generated/tibcotunnelrouteCR.yaml"
    exec: 
     timeout: 1m
     script: 
        cmd: "${ENV.fnSh}"
        args: ["deployResourse", "./generated/tibcotunnelrouteCR.yaml"]
        capture:
         stdout:
           - name: output
             match: "((?s).*)"
         stderr:
            - name: outerr
              match: "((?s).*)"
    expect:
     - name: status
       operator: equal
       value: 0

# Deploy ClientAppn Deployments
  - name: TCC3539_deployClientAppOldVersion
    type: foreground
    templates: 
      - input: "./resources/client-appUpdation.yaml"
        output: "./generated/client-appUpdation.yaml"
    exec: 
      timeout: 2m
      script:
        # cmd: "kubectl"
        # args: ["apply", "-f", "./generated/client-app.yaml"]
        cmd: "${ENV.fnSh}"
        args: ["deployResourse", "./generated/client-appUpdation.yaml"]       
    expect:
      - name: status
        operator: equal
        value: 0


# Status of Client Applications
  - name: TCC3539_status_of-clientAppn
    type: foreground
    exec: 
      timeout: 30s
      script: 
        # cmd: "kubectl"
        # args: ["get", "pods", "-n", "${NAMESPACE_TENANT}", "-o", "json", "--selector=app=http"]
        cmd: "${ENV.fnSh}"
        args: ["getPodNamesUsingSelector", "${NAMESPACE_TENANT}", "app=http"]
        capture:
          stdout:
            - name: running_state
              matchType: jsonpath
              match: "{.items[*].status.phase}"
            - name: capture_pod_name
              matchType: jsonpath
              match: "{.items[0].metadata.name}"
    expect:
      - name: status
        operator: equal
        value: 0
      - name: running_state
        operator: contains
        value: "Running"
      - name: running_state
        operator: notContains
        value: "Pending"
    repeat:
      count: 6
      until: success
      sleep: 5s  

# TibcoTunnel COnnect
  - name: TCC3539_tibtunnelConnect
    type: background
    exec:
      script:
        cmd: "/bin/bash"
        args: ["-c", "timeout 100s ./tibtunnel connect -d --remote-debug -s 8080:localhost:8080 https://${FQDN}/${ENDPOINT} -l $PWD/tibtunnelLog-3539" ]

# sleep
  - name: TCC3539_sleepCommand
    type: foreground
    exec:
      script:
        cmd: "sleep"
        args: ["30"]


# Deploy ClientAppn Deployments
  - name: TCC3539_deployClientAppLatestVersion
    type: foreground
    templates: 
      - input: "./resources/client-app.yaml"
        output: "./generated/client-app.yaml"
    exec: 
      timeout: 2m
      script:
        # cmd: "kubectl"
        # args: ["apply", "-f", "./generated/client-app.yaml"]
        cmd: "${ENV.fnSh}"
        args: ["deployResourse", "./generated/client-app.yaml"]       
    expect:
      - name: status
        operator: equal
        value: 0
# sleep
  - name: TCC3539_sleepCommand
    type: foreground
    exec:
      script:
        cmd: "sleep"
        args: ["30"]
# Status of Client Applications
  - name: TCC3539_status_of-clientAppn
    type: foreground
    exec: 
      timeout: 30s
      script: 
        # cmd: "kubectl"
        # args: ["get", "pods", "-n", "${NAMESPACE_TENANT}", "-o", "json", "--selector=app=http"]
        cmd: "${ENV.fnSh}"
        args: ["getPodNamesUsingSelector", "${NAMESPACE_TENANT}", "app=http"]
        capture:
          stdout:
            - name: running_state
              matchType: jsonpath
              match: "{.items[*].status.phase}"
            - name: capture_pod_name
              matchType: jsonpath
              match: "{.items[0].metadata.name}"
    expect:
      - name: status
        operator: equal
        value: 0
      - name: running_state
        operator: contains
        value: "Running"
      - name: running_state
        operator: notContains
        value: "Pending"
    repeat:
      count: 6
      until: success
      sleep: 5s 



# Tibtunnel logs for 
  - name: TCC3479_tibtunnelLogValidate
    type: foreground
    exec:
      script:
        cmd: "/bin/bash"
       # args: ["-c", "awk '/PING/{print}' /Users/sugandhi/Desktop/GITRepository/Regression/Hybrid-Proxy-Operator-Regression/tibtunnelLog-3395 &&  '/PONG/{print}' /Users/sugandhi/Desktop/GITRepository/Regression/Hybrid-Proxy-Operator-Regression/tibtunnelLog-3395"] 
        args: ["-c", "cat $PWD/tibtunnelLog-3539 | grep 'REMOVE_TAP' "]  
        capture:
          stdout:
            - name: closeTunnelOutput
              match: "((?s).*)"
    expect:
      - name: status
        operator: equal
        value: 0
      - name: closeTunnelOutput
        operator: containsStr
        value: "REMOVE_TAP"
    repeat:
      count: 6
      until: success
      sleep: 2s

# Tibtunnel logs for 
  - name: TCC3479_tibtunnelLogValidate2
    type: foreground
    exec:
      script:
        cmd: "/bin/bash"
       # args: ["-c", "awk '/PING/{print}' /Users/sugandhi/Desktop/GITRepository/Regression/Hybrid-Proxy-Operator-Regression/tibtunnelLog-3395 &&  '/PONG/{print}' /Users/sugandhi/Desktop/GITRepository/Regression/Hybrid-Proxy-Operator-Regression/tibtunnelLog-3395"] 
        args: ["-c", "cat $PWD/tibtunnelLog-3539 | grep 'ADD_TAP' "]  
        capture:
          stdout:
            - name: closeTunnelOutput1
              match: "((?s).*)"
              matchType: regexp
    expect:
      - name: status
        operator: equal
        value: 0
      - name: closeTunnelOutput1
        operator: containsStr
        value: "ADD_TAP"
    repeat:
      count: 6
      until: success
      sleep: 2s

  - name: TCC3539_sleepCommand
    type: foreground
    exec:
      script:
        cmd: "sleep"
        args: ["65"]
 
# Execution Output
  - name: INFO_______________TCC-3539_____testcasecompletion
    type: foreground
    exec:
      timeout: 2s
      script:
        cmd: "echo"
        args: ["TCC-3539:Customer_updates_client_applicatio_when_tunnel_is_established Executed Successfully"]
    expect:
      - name: status
        operator: equal
        value: 0
