#TibcoTunnelRoute CR for multiple deployments
apiVersion: cloud.tibco.com/v1
kind: TibcoTunnelRoute
metadata:
  name: ${META_DATA_NAME}
  namespace: ${NAMESPACE_TENANT}
spec:
  selector:
    tunnel.cloud.tibco.com/accessKeyId: accessKeyId1
  endpoint:
    path: /${ENDPOINT}               
    fqdn: ${FQDN}
    config: accesskey
    configVariables:
      ACCESS_KEY_HASH: "${suite.setup.secretKey_hashKey.accesshash}"
