apiVersion: cloud.tibco.com/v1
kind: TibcoTunnelRoute
metadata:
  name: tcp-client-vs
  namespace: aws-compute-tibco-tenant-x
spec:
  selector:
    app.kubernetes.io/name: tcp-client
  endpoint:
    path: /tcp-client3             
    fqdn: datascience-tun.compute-dev.eu-west-1.tibcoapps.net
    config: accesskey
    configVariables:
      ACCESS_KEY_HASH: "{PBKDF2-43}40000:wdfgdgfhhgm:wCyFxmH9RA1JcitdpGBiwPmFl3AQi8m2HGJUIo2KiVc"    #here hash is entered wrong manually